### ISSUE TITLE
Input shown in top-left of document in Firefox

### ISSUE THREAD

**Issue by Jinksi** [superhighfives/iwnlyg#1]
It looks like this is a bug caused by Modernizr, and has been patched: https://github.com/Modernizr/Modernizr/pull/1514

Should be fixed by updating to [Modernizr 3.2.0+](https://github.com/Modernizr/Modernizr/blob/b40f3afa852cecbba12076a99ec7c145c96c34ff/CHANGELOG.md#v320)

Using Firefox 74.0b9 

Screenshot:  

![Screen Shot 2020-03-09 at 10 58 52 am](https://user-images.githubusercontent.com/3147296/76174767-fe9f7900-61f4-11ea-95d3-3cbca2d31860.png)

**Comment by superhighfives** [comment]
Hey, thanks for pointing this out. Will definitely look at updating modernizr. 👍
